apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
      tier: zookeeper
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
        tier: zookeeper
        track: stable
    spec:
      containers:
        - name: zookeeper
          image: digitalwonderland/zookeeper
          ports:
          - containerPort: 2181
          env:
          - name: ZOOKEEPER_ID
            value: "1"
          - name: ZOOKEEPER_SERVER_1
            value: zoo1
