apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos
spec:
  selector:
    matchLabels:
      app: videos
      tier: videos
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: videos
        tier: videos
        track: stable
    spec:
      containers:
        - name: videos
          image: backend_videos
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_HOST
              value: videos-db-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: db
            - name: KAFKA_SERVER   
              value: kafka-service:9092
            - name: KAFKA_GROUP_ID   
              value: videos
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent