apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-db
spec:
  selector:
    matchLabels:
      app: videos-db
      tier: videos-db
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: videos-db
        tier: videos-db
        track: stable
    spec:
      containers:
        - name: videos-db
          image: postgres
          env:
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_DB
            value: "db"
          ports:
            - name: http
              containerPort: 5432
          volumeMounts:
          - name: videos-db-volume
            mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
      - name: videos-db-volume
        persistentVolumeClaim:
          claimName: videos-db-volume-claim
