apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-db
spec:
  selector:
    matchLabels:
      app: chat-db
      tier: chat-db
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-db
        tier: chat-db
        track: stable
    spec:
      containers:
        - name: chat-db
          image: postgres
          env:
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_DB
            value: "db"
          ports:
            - name: http
              containerPort: 5432
          volumeMounts:
          - name: chat-db-volume
            mountPath: /var/lib/postgresql/data

      volumes:
      - name: chat-db-volume
        persistentVolumeClaim:
          claimName: chat-db-volume-claim
