apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms
spec:
  selector:
    matchLabels:
      app: rooms
      tier: rooms
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: rooms
        tier: rooms
        track: stable
    spec:
      containers:
        - name: rooms
          image: backend_rooms
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_HOST
              value: rooms-db-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: db
            - name: KAFKA_SERVER   
              value: kafka-service:9092
            - name: KAFKA_GROUP_ID   
              value: rooms
          ports:
            - name: http
              containerPort: 8000

          imagePullPolicy: IfNotPresent